### ISSUE TITLE
Several possible bugs: incomplete folder generation; precise step will not initialize

### ISSUE THREAD

**Issue by kgallik** [bleach1by1/BIRDS_plugin#7]
I am testing the BIRDS plugin using the sample dataset provided (YH298). When creating the cache path in the first step of BIRDS, only two folders are generated: cache and registration, the instructions leave the user under the impression that the 5 folders mentioned are created when the cache path is selected. I have manually created the missing folders for the plugin to move forward in the plugin. At the end of the coarse step, the plugin log indicates that it ran successfully, but when the precise tab is selected, the following Exception occurs and the fuseImage is not opened:

Exception in thread "pool-2-thread-110" java.lang.NoSuchMethodError: org.apache.poi.hssf.usermodel.HSSFCell.getCellType()I
	at I.utils.ExcelTools.getData(ExcelTools.java:76)
	at I.precise.main.PreciseRegistration.addMouseListener(PreciseRegistration.java:84)
	at I.plugin.BirdsPlugin$4.lambda$0(BirdsPlugin.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

I am using Fiji version 1.54f.

Additionally, it is unclear how the python environment should be used with this plugin. Does Imaris need to be directed to this specific environment or is there a step in BIRDS that requires this environment?

Thank you for your help!

**Comment by rmd13** [comment]
...the plugin log indicates...
Please do not touch mouse or keyboard until OK dialogue appears, then you switch to Precise tab.
